---
- name: Repository configuration on all managed hosts
  hosts: all
  tasks:
    - name: Create BaseOS repository 
      ansible.builtin.yum_repository:
        name: "BaseOS"
        description: "BaseOS Description"
        baseurl: http://content/rhel9.0/x86_64/dvd/BaseOS
        gpgcheck: yes
        gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release
        enabled: yes

    - name: Create AppStream repository
      ansible.builtin.yum_repository:
        name: "AppStream"
        description: "AppStream Description"
        baseurl: http://content.example.com/rhel9.0/x86_64/dvd/AppStream
        gpgcheck: yes
        gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release
        enabled: yes

