---
- name: Create a cron job
  hosts: all
  tasks:

    - name: Cronjob for logger
      ansible.builtin.cron:
        name: Create logger
        user: student
        minute: "*/2"
        job: logger "EX294 in progress"
        state: present
