---
- name: collect all node information
  hosts: all
  tasks:

    - name: copy the template to managed node
      ansible.builtin.template:
        src: myhosts.j2
        dest: /etc/hosts
      when: inventory_hostname in groups['dev']

