---
- name: hwreport 
  hosts: all
  ignore_errors: yes
  tasks: 

    - name: Download the file
      ansible.builtin.get_url:
        url: http://content.example.com/rhel9.0/x86_64/dvd/media.repo
        dest: /root/hwreport.txt

    - name: Collect Report 1
      ansible.builtin.set_fact:
        HOSTNAME: "{{ ansible_hostname }}"
        MEMORY: "{{ ansible_memtotal_mb }}"
        BIOS: "{{ ansible_bios_version }}"
        CPU: "{{ ansible_processor }}"
        DISK_SIZE_VDA: "{{ ansible_devices['vda']['size'] }}"

    - name: Collect Report 2
      ansible.builtin.set_fact:
        DISK_SIZE_VDB: "{{ ansible_devices['vdb']['size'] }}"

    - name: Copy the content to the managed node
      ansible.builtin.copy:
        content:    |
          #hwreport
          HOSTNAME={{ HOSTNAME  | default('NONE') }}
          MEMORY={{ MEMORY  | default('NONE') }}
          BIOS={{ BIOS  | default('NONE') }}
          CPU={{ CPU  | default('NONE') }}
          DISK_SIZE_VDA={{ DISK_SIZE_VDA  | default('NONE') }}
          DISK_SIZE_VDB={{ DISK_SIZE_VDA  | default('NONE') }}
        dest: /root/hwreport.txt
